apiVersion: apps/v1
kind: Deployment

metadata:
  name: gitops-web

spec:
  replicas: 3

  selector:
    matchLabels:
      app: gitops-web

  template:
    metadata:
      labels:
        app: gitops-web

    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"

        - name: cpu-stress
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - "while true; do :; done"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
